"""Initial Migration

Revision ID: 86ddeaad93bd
Revises: 877c17f0c7c8
Create Date: 2021-09-29 19:47:07.056169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ddeaad93bd'
down_revision = '877c17f0c7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('product_name', sa.String(length=100), nullable=False))
    op.drop_column('items', 'name')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('items', 'product_name')
    # ### end Alembic commands ###
