"""Re-Initial Migration

Revision ID: 877c17f0c7c8
Revises: 9aa9053e55c7
Create Date: 2021-09-29 18:59:34.776865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877c17f0c7c8'
down_revision = '9aa9053e55c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('items', 'imageurl',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('items', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('items', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('items', 'imageurl',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
